stageManager working with modules.

diff --git a/bin/stageManager b/bin/stageManager
--- a/bin/stageManager
+++ b/bin/stageManager
@@ -117,7 +117,7 @@ if [ -z $PRODUCT ]; then
     usage
 fi
 
-PRODUCT_DIR=$(eups list -s -d $PRODUCT)
+eval PRODUCT_DIR=\$$(echo $(echo ${PRODUCT}_DIR | awk '{ print toupper($0) }'))
 
 if test -z "$PRODUCT_DIR"; then
     if [ $verbose = 1 ]; then
@@ -126,9 +126,9 @@ if test -z "$PRODUCT_DIR"; then
 
     module -v load $PRODUCT # > /dev/null 2>&1
 
-    PRODUCT_DIR=$(eups list -s -d $PRODUCT)
+    eval PRODUCT_DIR=\$$(echo $(echo ${PRODUCT}_DIR | awk '{ print toupper($0) }'))
     if test -z "$PRODUCT_DIR"; then
-	echo "Product $PRODUCT wasn't not setup, and I failed to set it up for you" >&2
+	echo "Product $PRODUCT $PRODUCT_DIR wasn't not setup, and I failed to set it up for you" >&2
 	exit 1
     fi
 fi
